### ISSUE TITLE
How to set validation

### ISSUE THREAD

**Issue by tamaki-tech** [mskocik/svelty-picker#26]
Hello! I'm trying to use svelty-picker in my application.
I get an error when I set validationActions.

Is this my source code wrong?

code: 
```js
      <SveltyPicker
        name="joinedAt"
        bind:value={joinedAt}
        validatorAction={[required]} // set svelte-use-form validations.
        format={dateInputUtils.PATTERN_YYYY_MM}
        placeholder="2000/01"
        inputClasses="border border-gray-300 text-xl p-1"
        weekStart={dateInputUtils.WEEK_START}
        i18n={dateInputUtils.LOCALE}
      />
```

error: 
```
validators.js:2 Uncaught (in promise) TypeError: value.trim is not a function
    at required (validators.js:2:18)
    at mount (SveltyPicker.svelte? [sm]:235:2)
    at Object.targetCmp.$$.fragment.m (svelte-hooks.js:216:24)
    at mount_component (index.mjs:1798:26)
    at mount (CareerEditModal.svelte:283:51)
    at Object.targetCmp.$$.fragment.m (svelte-hooks.js:216:24)
    at mount_component (index.mjs:1798:26)
    at Object.mount [as m] ([id].svelte:169:25)
    at Object.update [as p] ([id].svelte:166:25)
    at Object.update [as p] ([id].svelte:83:27)

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'form')
    at setupValidation (validatorsAction.js:16:43)
```

**Comment by mskocik** [comment]
You need to pass `validators` from `svelte-use-form` as first item of `validatorAction` array:

```svelte
import { validators, required } from 'svelte-use-form'

 <SveltyPicker
  name="joinedAt"
  bind:value={joinedAt}
  validatorAction={[validators, required]} // set svelte-use-form validations.
  format={dateInputUtils.PATTERN_YYYY_MM}
  placeholder="2000/01"
  inputClasses="border border-gray-300 text-xl p-1"
  weekStart={dateInputUtils.WEEK_START}
  i18n={dateInputUtils.LOCALE}
/>
```

**Comment by tamaki-tech** [comment]
thank you for your advice! The problem has been solved.🙏

**Comment by mskocik** [comment]
So you can close the issue, right?
